# Generated by Django 3.1.2 on 2020-11-06 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tLoans', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShortTerm',
            new_name='Short_term',
        ),
    ]
