# Generated by Django 3.1.2 on 2020-11-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tLoans', '0002_auto_20201106_1210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='long_term',
            options={'verbose_name': 'Long Term', 'verbose_name_plural': 'Long Terms'},
        ),
        migrations.AlterModelOptions(
            name='short_term',
            options={'verbose_name': 'Short Term', 'verbose_name_plural': 'Short Terms'},
        ),
        migrations.AddField(
            model_name='long_term',
            name='amount_left',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
