# Generated by Django 3.1.2 on 2020-11-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tLoans', '0005_remove_long_term_long_term_interest_repayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='long_term',
            name='amount_left',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
