# Generated by Django 3.1.2 on 2020-11-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tLoans', '0006_auto_20201108_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='long_term',
            name='amount_left',
            field=models.IntegerField(),
        ),
    ]
