# Generated by Django 3.1.2 on 2020-11-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tLoans', '0007_auto_20201109_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='long_term',
            name='amount_left',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
