# Generated by Django 3.1.2 on 2020-11-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tLoans', '0008_auto_20201109_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booster',
            name='name',
            field=models.CharField(choices=[('AG', 'Agriculture'), ('ED', 'Education')], max_length=20),
        ),
    ]
