# Generated by Django 3.1.2 on 2020-11-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tLoans', '0010_auto_20201111_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booster',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
