# Generated by Django 3.1.2 on 2020-11-13 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tLoans', '0012_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
